/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yuan_cn_jni_TheJniTest */

#ifndef _Included_com_yuan_cn_jni_TheJniTest
#define _Included_com_yuan_cn_jni_TheJniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yuan_cn_jni_TheJniTest
 * Method:    helloFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yuan_cn_jni_TheJniTest_helloFromC
  (JNIEnv *, jclass);

/*
 * Class:     com_yuan_cn_jni_TheJniTest
 * Method:    passwordFromC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_yuan_cn_jni_TheJniTest_passwordFromC
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
